// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3c8dGy9VcdOcAlPqWZPMLH6VFq5RbpYc',
    appId: '1:328188996700:web:e990bb2171170360878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    authDomain: 'talkease-285a9.firebaseapp.com',
    storageBucket: 'talkease-285a9.appspot.com',
    measurementId: 'G-TG9T4DF7SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IBRwTqV1ZCsr0u4tISPwdQpfbOTGS1A',
    appId: '1:328188996700:android:2b7be6cbc906f7f4878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    storageBucket: 'talkease-285a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpgVROWKSxkZFSKpDpsOBUErvcy_GIMU',
    appId: '1:328188996700:ios:966c4f22cf2b4c9a878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    storageBucket: 'talkease-285a9.appspot.com',
    androidClientId: '328188996700-6988k90c1fsklch003nb9a2l3afnl2le.apps.googleusercontent.com',
    iosClientId: '328188996700-8k2141lh88u0boikn66062bpqtouhcqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZpgVROWKSxkZFSKpDpsOBUErvcy_GIMU',
    appId: '1:328188996700:ios:966c4f22cf2b4c9a878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    storageBucket: 'talkease-285a9.appspot.com',
    androidClientId: '328188996700-6988k90c1fsklch003nb9a2l3afnl2le.apps.googleusercontent.com',
    iosClientId: '328188996700-8k2141lh88u0boikn66062bpqtouhcqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3c8dGy9VcdOcAlPqWZPMLH6VFq5RbpYc',
    appId: '1:328188996700:web:806b76f55ac7503e878a99',
    messagingSenderId: '328188996700',
    projectId: 'talkease-285a9',
    authDomain: 'talkease-285a9.firebaseapp.com',
    storageBucket: 'talkease-285a9.appspot.com',
    measurementId: 'G-FLPW3C7M1V',
  );
}
